export const FETCH_SELLERS_COUNT = 'FETCH_SELLERS_COUNT';
export const FETCH_SELLERS_SUCCESS_COUNT = 'FETCH_SELLERS_SUCCESS_COUNT';
export const FETCH_SELLERS_FAILED_COUNT = 'FETCH_SELLERS_FAILED_COUNT'

export const FETCH_USERS_COUNT = 'FETCH_USERS_COUNT';
export const FETCH_USERS_SUCCESS_COUNT = 'FETCH_USERS_SUCCESS_COUNT';
export const FETCH_USERS_FAILED_COUNT = 'FETCH_USERS_FAILED_COUNT'