export const FETCH_SELLERS = 'FETCH_SELLERS';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';
export const FETCH_SELLERS_FAILED = 'FETCH_SELLERS_FAILED'

// export const FETCH_USERS = 'FETCH_USERS';
// export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
// export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'